# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - JINA_API_KEY=${JINA_API_KEY}
    volumes:
      - ./back-end:/app
    networks:
      - studylore-network

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./front-end:/app
      - /app/node_modules
      - /app/.next
    networks:
      - studylore-network


networks:
  studylore-network:
    driver: bridge
